"""empty message

Revision ID: 5995f2500128
Revises: ca7e86724411
Create Date: 2025-04-01 21:03:40.067194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5995f2500128'
down_revision = 'ca7e86724411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commet_text', sa.String(length=120), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('coment')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_text', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('post_text')

    op.create_table('coment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('commet_text', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='coment_author_id_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='coment_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='coment_pkey')
    )
    op.drop_table('comment')
    # ### end Alembic commands ###
