"""empty message

Revision ID: 70bd87c05ae3
Revises: cd4c0ebe2254
Create Date: 2025-03-28 04:19:57.576756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bd87c05ae3'
down_revision = 'cd4c0ebe2254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commet_text', sa.String(length=120), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commet')
    # ### end Alembic commands ###
