"""empty message

Revision ID: 70d9c4da9aee
Revises: 9bcec8025151
Create Date: 2025-03-28 03:59:37.084435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d9c4da9aee'
down_revision = '9bcec8025151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('media_email_key', type_='unique')
        batch_op.drop_constraint('media_firstname_key', type_='unique')
        batch_op.drop_constraint('media_lastname_key', type_='unique')
        batch_op.drop_constraint('media_username_key', type_='unique')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])
        batch_op.drop_column('email')
        batch_op.drop_column('username')
        batch_op.drop_column('firstname')
        batch_op.drop_column('password')
        batch_op.drop_column('is_active')
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('media_username_key', ['username'])
        batch_op.create_unique_constraint('media_lastname_key', ['lastname'])
        batch_op.create_unique_constraint('media_firstname_key', ['firstname'])
        batch_op.create_unique_constraint('media_email_key', ['email'])
        batch_op.drop_column('post_id')
        batch_op.drop_column('url')
        batch_op.drop_column('type')

    op.drop_table('post')
    # ### end Alembic commands ###
