"""empty message

Revision ID: ca7e86724411
Revises: 70bd87c05ae3
Create Date: 2025-04-01 20:06:07.884899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7e86724411'
down_revision = '70bd87c05ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commet_text', sa.String(length=120), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('commet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('commet_text', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='commet_author_id_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='commet_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='commet_pkey')
    )
    op.drop_table('likes')
    op.drop_table('coment')
    # ### end Alembic commands ###
